// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `Hashnet.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package one.inve.localfullnode2.rpc;

public interface RegisterPrx extends com.zeroc.Ice.ObjectPrx
{
    default String getLocalFullNodeList(String pubkey)
    {
        return getLocalFullNodeList(pubkey, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getLocalFullNodeList(String pubkey, java.util.Map<String, String> context)
    {
        return _iceI_getLocalFullNodeListAsync(pubkey, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getLocalFullNodeListAsync(String pubkey)
    {
        return _iceI_getLocalFullNodeListAsync(pubkey, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getLocalFullNodeListAsync(String pubkey, java.util.Map<String, String> context)
    {
        return _iceI_getLocalFullNodeListAsync(pubkey, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getLocalFullNodeListAsync(String iceP_pubkey, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getLocalFullNodeList", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_pubkey);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getNodeShardInfo(String pubkey)
    {
        return getNodeShardInfo(pubkey, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getNodeShardInfo(String pubkey, java.util.Map<String, String> context)
    {
        return _iceI_getNodeShardInfoAsync(pubkey, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getNodeShardInfoAsync(String pubkey)
    {
        return _iceI_getNodeShardInfoAsync(pubkey, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getNodeShardInfoAsync(String pubkey, java.util.Map<String, String> context)
    {
        return _iceI_getNodeShardInfoAsync(pubkey, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getNodeShardInfoAsync(String iceP_pubkey, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getNodeShardInfo", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_pubkey);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getShardInfoList()
    {
        return getShardInfoList(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getShardInfoList(java.util.Map<String, String> context)
    {
        return _iceI_getShardInfoListAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getShardInfoListAsync()
    {
        return _iceI_getShardInfoListAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getShardInfoListAsync(java.util.Map<String, String> context)
    {
        return _iceI_getShardInfoListAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getShardInfoListAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getShardInfoList", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String registerLocalFullNode(String pubkey, String address)
    {
        return registerLocalFullNode(pubkey, address, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String registerLocalFullNode(String pubkey, String address, java.util.Map<String, String> context)
    {
        return _iceI_registerLocalFullNodeAsync(pubkey, address, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> registerLocalFullNodeAsync(String pubkey, String address)
    {
        return _iceI_registerLocalFullNodeAsync(pubkey, address, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> registerLocalFullNodeAsync(String pubkey, String address, java.util.Map<String, String> context)
    {
        return _iceI_registerLocalFullNodeAsync(pubkey, address, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_registerLocalFullNodeAsync(String iceP_pubkey, String iceP_address, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerLocalFullNode", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_pubkey);
                     ostr.writeString(iceP_address);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getNrgPrice()
    {
        return getNrgPrice(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getNrgPrice(java.util.Map<String, String> context)
    {
        return _iceI_getNrgPriceAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getNrgPriceAsync()
    {
        return _iceI_getNrgPriceAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getNrgPriceAsync(java.util.Map<String, String> context)
    {
        return _iceI_getNrgPriceAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getNrgPriceAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getNrgPrice", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RegisterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), RegisterPrx.class, _RegisterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RegisterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), RegisterPrx.class, _RegisterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RegisterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), RegisterPrx.class, _RegisterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static RegisterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), RegisterPrx.class, _RegisterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static RegisterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, RegisterPrx.class, _RegisterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static RegisterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, RegisterPrx.class, _RegisterPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default RegisterPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (RegisterPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default RegisterPrx ice_adapterId(String newAdapterId)
    {
        return (RegisterPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default RegisterPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (RegisterPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default RegisterPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (RegisterPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default RegisterPrx ice_invocationTimeout(int newTimeout)
    {
        return (RegisterPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default RegisterPrx ice_connectionCached(boolean newCache)
    {
        return (RegisterPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default RegisterPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (RegisterPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RegisterPrx ice_secure(boolean b)
    {
        return (RegisterPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default RegisterPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (RegisterPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default RegisterPrx ice_preferSecure(boolean b)
    {
        return (RegisterPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default RegisterPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (RegisterPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default RegisterPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (RegisterPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default RegisterPrx ice_collocationOptimized(boolean b)
    {
        return (RegisterPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default RegisterPrx ice_twoway()
    {
        return (RegisterPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default RegisterPrx ice_oneway()
    {
        return (RegisterPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default RegisterPrx ice_batchOneway()
    {
        return (RegisterPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default RegisterPrx ice_datagram()
    {
        return (RegisterPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default RegisterPrx ice_batchDatagram()
    {
        return (RegisterPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default RegisterPrx ice_compress(boolean co)
    {
        return (RegisterPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default RegisterPrx ice_timeout(int t)
    {
        return (RegisterPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default RegisterPrx ice_connectionId(String connectionId)
    {
        return (RegisterPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default RegisterPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (RegisterPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::one::inve::rpc::fullnode::Register";
    }
}
