// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ic.proto

package ic

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestUpdateMeta struct {
	Meta                 []*MetaData `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RequestUpdateMeta) Reset()         { *m = RequestUpdateMeta{} }
func (m *RequestUpdateMeta) String() string { return proto.CompactTextString(m) }
func (*RequestUpdateMeta) ProtoMessage()    {}
func (*RequestUpdateMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{0}
}

func (m *RequestUpdateMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUpdateMeta.Unmarshal(m, b)
}
func (m *RequestUpdateMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUpdateMeta.Marshal(b, m, deterministic)
}
func (m *RequestUpdateMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUpdateMeta.Merge(m, src)
}
func (m *RequestUpdateMeta) XXX_Size() int {
	return xxx_messageInfo_RequestUpdateMeta.Size(m)
}
func (m *RequestUpdateMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUpdateMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUpdateMeta proto.InternalMessageInfo

func (m *RequestUpdateMeta) GetMeta() []*MetaData {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ResponseUpdateMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUpdateMeta) Reset()         { *m = ResponseUpdateMeta{} }
func (m *ResponseUpdateMeta) String() string { return proto.CompactTextString(m) }
func (*ResponseUpdateMeta) ProtoMessage()    {}
func (*ResponseUpdateMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{1}
}

func (m *ResponseUpdateMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUpdateMeta.Unmarshal(m, b)
}
func (m *ResponseUpdateMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUpdateMeta.Marshal(b, m, deterministic)
}
func (m *ResponseUpdateMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUpdateMeta.Merge(m, src)
}
func (m *ResponseUpdateMeta) XXX_Size() int {
	return xxx_messageInfo_ResponseUpdateMeta.Size(m)
}
func (m *ResponseUpdateMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUpdateMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUpdateMeta proto.InternalMessageInfo

type RequestFindMembers struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFindMembers) Reset()         { *m = RequestFindMembers{} }
func (m *RequestFindMembers) String() string { return proto.CompactTextString(m) }
func (*RequestFindMembers) ProtoMessage()    {}
func (*RequestFindMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{2}
}

func (m *RequestFindMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFindMembers.Unmarshal(m, b)
}
func (m *RequestFindMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFindMembers.Marshal(b, m, deterministic)
}
func (m *RequestFindMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFindMembers.Merge(m, src)
}
func (m *RequestFindMembers) XXX_Size() int {
	return xxx_messageInfo_RequestFindMembers.Size(m)
}
func (m *RequestFindMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFindMembers.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFindMembers proto.InternalMessageInfo

type ResponseFindMembers struct {
	FindMember           []*ResponseFindMember `protobuf:"bytes,1,rep,name=findMember,proto3" json:"findMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResponseFindMembers) Reset()         { *m = ResponseFindMembers{} }
func (m *ResponseFindMembers) String() string { return proto.CompactTextString(m) }
func (*ResponseFindMembers) ProtoMessage()    {}
func (*ResponseFindMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{3}
}

func (m *ResponseFindMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFindMembers.Unmarshal(m, b)
}
func (m *ResponseFindMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFindMembers.Marshal(b, m, deterministic)
}
func (m *ResponseFindMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFindMembers.Merge(m, src)
}
func (m *ResponseFindMembers) XXX_Size() int {
	return xxx_messageInfo_ResponseFindMembers.Size(m)
}
func (m *ResponseFindMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFindMembers.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFindMembers proto.InternalMessageInfo

func (m *ResponseFindMembers) GetFindMember() []*ResponseFindMember {
	if m != nil {
		return m.FindMember
	}
	return nil
}

type ResponseFindMember struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string      `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Meta                 []*MetaData `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseFindMember) Reset()         { *m = ResponseFindMember{} }
func (m *ResponseFindMember) String() string { return proto.CompactTextString(m) }
func (*ResponseFindMember) ProtoMessage()    {}
func (*ResponseFindMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{4}
}

func (m *ResponseFindMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFindMember.Unmarshal(m, b)
}
func (m *ResponseFindMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFindMember.Marshal(b, m, deterministic)
}
func (m *ResponseFindMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFindMember.Merge(m, src)
}
func (m *ResponseFindMember) XXX_Size() int {
	return xxx_messageInfo_ResponseFindMember.Size(m)
}
func (m *ResponseFindMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFindMember.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFindMember proto.InternalMessageInfo

func (m *ResponseFindMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseFindMember) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ResponseFindMember) GetMeta() []*MetaData {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MetaData struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaData) Reset()         { *m = MetaData{} }
func (m *MetaData) String() string { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()    {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{5}
}

func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaData.Unmarshal(m, b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaData.Marshal(b, m, deterministic)
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return xxx_messageInfo_MetaData.Size(m)
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetaData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Member struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Meta                 []*MetaData `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f50b9a86045289, []int{6}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetMeta() []*MetaData {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestUpdateMeta)(nil), "ic.RequestUpdateMeta")
	proto.RegisterType((*ResponseUpdateMeta)(nil), "ic.ResponseUpdateMeta")
	proto.RegisterType((*RequestFindMembers)(nil), "ic.RequestFindMembers")
	proto.RegisterType((*ResponseFindMembers)(nil), "ic.ResponseFindMembers")
	proto.RegisterType((*ResponseFindMember)(nil), "ic.ResponseFindMember")
	proto.RegisterType((*MetaData)(nil), "ic.MetaData")
	proto.RegisterType((*Member)(nil), "ic.Member")
}

func init() { proto.RegisterFile("ic.proto", fileDescriptor_49f50b9a86045289) }

var fileDescriptor_49f50b9a86045289 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x65, 0xdb, 0xda, 0xd6, 0xd1, 0x43, 0x8d, 0xb5, 0x2e, 0x3d, 0x95, 0x05, 0xa1, 0xa7, 0x3d,
	0xac, 0xe8, 0xc5, 0x93, 0xad, 0xe8, 0xa9, 0x97, 0x15, 0xc1, 0x93, 0x90, 0x26, 0x53, 0x08, 0xa6,
	0xc9, 0xba, 0xc9, 0x16, 0xfc, 0x9f, 0xfe, 0x20, 0xc9, 0x7e, 0xb4, 0xf1, 0x1b, 0xbc, 0xcd, 0xbc,
	0x7d, 0x79, 0x6f, 0x66, 0xde, 0x42, 0x5f, 0xb0, 0x38, 0xcb, 0xb5, 0xd5, 0xa4, 0x25, 0x58, 0x74,
	0x01, 0x47, 0x29, 0xbe, 0x14, 0x68, 0xec, 0x43, 0xc6, 0xa9, 0xc5, 0x05, 0x5a, 0x4a, 0x26, 0xd0,
	0x59, 0xa3, 0xa5, 0x61, 0x30, 0x69, 0x4f, 0x0f, 0x92, 0xc3, 0x58, 0xb0, 0xd8, 0xe1, 0x37, 0xd4,
	0xd2, 0xb4, 0xfc, 0x12, 0x0d, 0x81, 0xa4, 0x68, 0x32, 0xad, 0x0c, 0xee, 0xde, 0x55, 0x68, 0x29,
	0x76, 0x2b, 0x14, 0x5f, 0xe0, 0x7a, 0x89, 0xb9, 0x89, 0x16, 0x70, 0xdc, 0x70, 0x3d, 0x98, 0x5c,
	0x02, 0xac, 0xb6, 0x6d, 0x6d, 0x35, 0x72, 0x56, 0x5f, 0xc9, 0xa9, 0xc7, 0x8c, 0x9e, 0x76, 0xd6,
	0x3b, 0x06, 0x21, 0xd0, 0x51, 0x74, 0x8d, 0x61, 0x30, 0x09, 0xa6, 0xfb, 0x69, 0x59, 0x3b, 0x8c,
	0x72, 0x9e, 0x87, 0xad, 0x0a, 0x73, 0xf5, 0x76, 0xb5, 0xf6, 0x8f, 0xab, 0x25, 0xd0, 0x6f, 0x10,
	0x32, 0x80, 0xf6, 0x33, 0xbe, 0xd6, 0xa2, 0xae, 0x24, 0x43, 0xd8, 0xdb, 0x50, 0x59, 0x60, 0x2d,
	0x5a, 0x35, 0xd1, 0x23, 0x74, 0x7f, 0x99, 0x23, 0x84, 0x9e, 0xf3, 0x46, 0x63, 0xea, 0x57, 0x4d,
	0xfb, 0xf7, 0x34, 0xc9, 0x5b, 0x00, 0xbd, 0xb9, 0x2c, 0x8c, 0xc5, 0x9c, 0x5c, 0x01, 0x78, 0x21,
	0x9d, 0x54, 0xb7, 0xfa, 0x94, 0xdd, 0xf8, 0xc3, 0x09, 0x3d, 0xfa, 0x1c, 0x06, 0xee, 0x5c, 0xd7,
	0x52, 0x6c, 0xb0, 0x89, 0x60, 0xe4, 0x49, 0x78, 0xd1, 0x8c, 0x4f, 0xbf, 0x8f, 0xc1, 0x90, 0x3b,
	0x18, 0xba, 0xf6, 0xbe, 0x30, 0x19, 0x32, 0x8b, 0xfc, 0xbf, 0x42, 0xb3, 0x33, 0x18, 0x6b, 0x85,
	0xb1, 0x50, 0x1b, 0x8c, 0xa5, 0x66, 0x54, 0xae, 0x0a, 0x29, 0x95, 0xe6, 0x98, 0xc4, 0x82, 0xcd,
	0x9a, 0x8d, 0x97, 0xdd, 0xf2, 0x47, 0x3d, 0x7f, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x69, 0x9a, 0xb3,
	0x22, 0xb4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	UpdateMeta(ctx context.Context, in *RequestUpdateMeta, opts ...grpc.CallOption) (*ResponseUpdateMeta, error)
	FindAliveMembers(ctx context.Context, in *RequestFindMembers, opts ...grpc.CallOption) (*ResponseFindMembers, error)
	FindSuspectedMembers(ctx context.Context, in *RequestFindMembers, opts ...grpc.CallOption) (*ResponseFindMembers, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) UpdateMeta(ctx context.Context, in *RequestUpdateMeta, opts ...grpc.CallOption) (*ResponseUpdateMeta, error) {
	out := new(ResponseUpdateMeta)
	err := c.cc.Invoke(ctx, "/ic.Cluster/UpdateMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) FindAliveMembers(ctx context.Context, in *RequestFindMembers, opts ...grpc.CallOption) (*ResponseFindMembers, error) {
	out := new(ResponseFindMembers)
	err := c.cc.Invoke(ctx, "/ic.Cluster/FindAliveMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) FindSuspectedMembers(ctx context.Context, in *RequestFindMembers, opts ...grpc.CallOption) (*ResponseFindMembers, error) {
	out := new(ResponseFindMembers)
	err := c.cc.Invoke(ctx, "/ic.Cluster/FindSuspectedMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	UpdateMeta(context.Context, *RequestUpdateMeta) (*ResponseUpdateMeta, error)
	FindAliveMembers(context.Context, *RequestFindMembers) (*ResponseFindMembers, error)
	FindSuspectedMembers(context.Context, *RequestFindMembers) (*ResponseFindMembers, error)
}

// UnimplementedClusterServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct {
}

func (*UnimplementedClusterServer) UpdateMeta(ctx context.Context, req *RequestUpdateMeta) (*ResponseUpdateMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMeta not implemented")
}
func (*UnimplementedClusterServer) FindAliveMembers(ctx context.Context, req *RequestFindMembers) (*ResponseFindMembers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAliveMembers not implemented")
}
func (*UnimplementedClusterServer) FindSuspectedMembers(ctx context.Context, req *RequestFindMembers) (*ResponseFindMembers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuspectedMembers not implemented")
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_UpdateMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdateMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).UpdateMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ic.Cluster/UpdateMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).UpdateMeta(ctx, req.(*RequestUpdateMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_FindAliveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFindMembers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).FindAliveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ic.Cluster/FindAliveMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).FindAliveMembers(ctx, req.(*RequestFindMembers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_FindSuspectedMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFindMembers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).FindSuspectedMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ic.Cluster/FindSuspectedMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).FindSuspectedMembers(ctx, req.(*RequestFindMembers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ic.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMeta",
			Handler:    _Cluster_UpdateMeta_Handler,
		},
		{
			MethodName: "FindAliveMembers",
			Handler:    _Cluster_FindAliveMembers_Handler,
		},
		{
			MethodName: "FindSuspectedMembers",
			Handler:    _Cluster_FindSuspectedMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ic.proto",
}
