// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchainInfo.proto

package vo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockchainInfo struct {
	Height               uint64   `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	CurrentBlockHash     []byte   `protobuf:"bytes,2,opt,name=CurrentBlockHash,proto3" json:"CurrentBlockHash,omitempty"`
	PreviousBlockHash    []byte   `protobuf:"bytes,3,opt,name=PreviousBlockHash,proto3" json:"PreviousBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockchainInfo) Reset()         { *m = BlockchainInfo{} }
func (m *BlockchainInfo) String() string { return proto.CompactTextString(m) }
func (*BlockchainInfo) ProtoMessage()    {}
func (*BlockchainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_899804d1677172c0, []int{0}
}

func (m *BlockchainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockchainInfo.Unmarshal(m, b)
}
func (m *BlockchainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockchainInfo.Marshal(b, m, deterministic)
}
func (m *BlockchainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockchainInfo.Merge(m, src)
}
func (m *BlockchainInfo) XXX_Size() int {
	return xxx_messageInfo_BlockchainInfo.Size(m)
}
func (m *BlockchainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockchainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockchainInfo proto.InternalMessageInfo

func (m *BlockchainInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockchainInfo) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *BlockchainInfo) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockchainInfo)(nil), "vo.BlockchainInfo")
}

func init() { proto.RegisterFile("blockchainInfo.proto", fileDescriptor_899804d1677172c0) }

var fileDescriptor_899804d1677172c0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xca, 0xc9, 0x4f,
	0xce, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0xf3, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0xcb, 0x57, 0x6a, 0x62, 0xe4, 0xe2, 0x73, 0x42, 0x91, 0x14, 0x12, 0xe3, 0x62,
	0xf3, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0xf2, 0x84,
	0xb4, 0xb8, 0x04, 0x9c, 0x4b, 0x8b, 0x8a, 0x52, 0xf3, 0x4a, 0xc0, 0x1a, 0x3c, 0x12, 0x8b, 0x33,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x30, 0xc4, 0x85, 0x74, 0xb8, 0x04, 0x03, 0x8a, 0x52,
	0xcb, 0x32, 0xf3, 0x4b, 0x8b, 0x11, 0x8a, 0x99, 0xc1, 0x8a, 0x31, 0x25, 0x92, 0xd8, 0xc0, 0xee,
	0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x0c, 0xdd, 0x0f, 0xa7, 0x00, 0x00, 0x00,
}
