package one.inve.contract.sig;

/**
 * 
 * 
 * Copyright © CHXX Co.,Ltd. All rights reserved.
 * 
 * @Description: SigMain is a utility entry to simulate general wallet's
 *               elliptic curve cryptography.
 * @author: Francis.Deng
 * @date: 2018年12月11日 下午3:16:23
 * @version: V1.0
 */
public class SigMain {
	/**
	 * <ul>
	 * 
	 * <li>java -jar yourjar one.inve.contract.sig.SigMain -T -O consig.conf</li>
	 * <p/>
	 * <li>-O (optional)output configuration template file(default "consig.conf")
	 * </li>
	 * 
	 * java -jar yourjar one.inve.contract.sig.SigMain -S -I consig.conf
	 * <p/>
	 * -N http://localhost:8888/v1/getNonce -O t.json
	 * 
	 * -I (optional)input configuration file 'consig.conf'(default
	 * 'consig.conf',generated by previous tool command.)
	 * <p/>
	 * -N (optional)the url from which system would get a nonce by address(default
	 * 'http://localhost:8888/v1/getNonce'),ensuring the endpoint is available
	 * <p/>
	 * -O (optional)output signing file(default 't.json')
	 * </ul>
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		Signature sig = new Signature();
		sig.run(args);

	}

}
