// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package one.inve.localfullnode2.chronicle.rpc;

public interface ByteStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ByteStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes data = 1;</code>
   * @return A list containing the data.
   */
  java.util.List<com.google.protobuf.ByteString> getDataList();
  /**
   * <code>repeated bytes data = 1;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated bytes data = 1;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  com.google.protobuf.ByteString getData(int index);
}
