// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.proto

package one.inve.localfullnode2.chronicle.rpc;

public final class Misc {
  private Misc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_WrappedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_WrappedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmisc.proto\022\003rpc\":\n\016WrappedMessage\022\023\n\013m" +
      "essageType\030\001 \001(\005\022\023\n\013messageBody\030\002 \001(\014B)\n" +
      "%one.inve.localfullnode2.chronicle.rpcP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_WrappedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_WrappedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_WrappedMessage_descriptor,
        new java.lang.String[] { "MessageType", "MessageBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
