// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package one.inve.localfullnode2.chronicle.rpc;

/**
 * Protobuf type {@code rpc.StringArray}
 */
public final class StringArray extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:rpc.StringArray)
		StringArrayOrBuilder {
	private static final long serialVersionUID = 0L;

	// Use StringArray.newBuilder() to construct.
	private StringArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private StringArray() {
		data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
	}

	@SuppressWarnings({ "unused" })
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new StringArray();
	}

	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	private StringArray(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		}
		int mutable_bitField0_ = 0;
		com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				case 10: {
					java.lang.String s = input.readStringRequireUtf8();
					if (!((mutable_bitField0_ & 0x00000001) != 0)) {
						data_ = new com.google.protobuf.LazyStringArrayList();
						mutable_bitField0_ |= 0x00000001;
					}
					data_.add(s);
					break;
				}
				default: {
					if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
						done = true;
					}
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		} catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		} finally {
			if (((mutable_bitField0_ & 0x00000001) != 0)) {
				data_ = data_.getUnmodifiableView();
			}
			this.unknownFields = unknownFields.build();
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return one.inve.localfullnode2.chronicle.rpc.Common.internal_static_rpc_StringArray_descriptor;
	}

	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return one.inve.localfullnode2.chronicle.rpc.Common.internal_static_rpc_StringArray_fieldAccessorTable
				.ensureFieldAccessorsInitialized(one.inve.localfullnode2.chronicle.rpc.StringArray.class,
						one.inve.localfullnode2.chronicle.rpc.StringArray.Builder.class);
	}

	public static final int DATA_FIELD_NUMBER = 1;
	private com.google.protobuf.LazyStringList data_;

	/**
	 * <code>repeated string data = 1;</code>
	 * 
	 * @return A list containing the data.
	 */
	public com.google.protobuf.ProtocolStringList getDataList() {
		return data_;
	}

	/**
	 * <code>repeated string data = 1;</code>
	 * 
	 * @return The count of data.
	 */
	public int getDataCount() {
		return data_.size();
	}

	/**
	 * <code>repeated string data = 1;</code>
	 * 
	 * @param index The index of the element to return.
	 * @return The data at the given index.
	 */
	public java.lang.String getData(int index) {
		return data_.get(index);
	}

	/**
	 * <code>repeated string data = 1;</code>
	 * 
	 * @param index The index of the value to return.
	 * @return The bytes of the data at the given index.
	 */
	public com.google.protobuf.ByteString getDataBytes(int index) {
		return data_.getByteString(index);
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		for (int i = 0; i < data_.size(); i++) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_.getRaw(i));
		}
		unknownFields.writeTo(output);
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		{
			int dataSize = 0;
			for (int i = 0; i < data_.size(); i++) {
				dataSize += computeStringSizeNoTag(data_.getRaw(i));
			}
			size += dataSize;
			size += 1 * getDataList().size();
		}
		size += unknownFields.getSerializedSize();
		memoizedSize = size;
		return size;
	}

	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof one.inve.localfullnode2.chronicle.rpc.StringArray)) {
			return super.equals(obj);
		}
		one.inve.localfullnode2.chronicle.rpc.StringArray other = (one.inve.localfullnode2.chronicle.rpc.StringArray) obj;

		if (!getDataList().equals(other.getDataList()))
			return false;
		if (!unknownFields.equals(other.unknownFields))
			return false;
		return true;
	}

	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		if (getDataCount() > 0) {
			hash = (37 * hash) + DATA_FIELD_NUMBER;
			hash = (53 * hash) + getDataList().hashCode();
		}
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(one.inve.localfullnode2.chronicle.rpc.StringArray prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code rpc.StringArray}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:rpc.StringArray)
			one.inve.localfullnode2.chronicle.rpc.StringArrayOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return one.inve.localfullnode2.chronicle.rpc.Common.internal_static_rpc_StringArray_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return one.inve.localfullnode2.chronicle.rpc.Common.internal_static_rpc_StringArray_fieldAccessorTable
					.ensureFieldAccessorsInitialized(one.inve.localfullnode2.chronicle.rpc.StringArray.class,
							one.inve.localfullnode2.chronicle.rpc.StringArray.Builder.class);
		}

		// Construct using
		// one.inve.localfullnode2.chronicle.rpc.StringArray.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		public Builder clear() {
			super.clear();
			data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			bitField0_ = (bitField0_ & ~0x00000001);
			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return one.inve.localfullnode2.chronicle.rpc.Common.internal_static_rpc_StringArray_descriptor;
		}

		public one.inve.localfullnode2.chronicle.rpc.StringArray getDefaultInstanceForType() {
			return one.inve.localfullnode2.chronicle.rpc.StringArray.getDefaultInstance();
		}

		public one.inve.localfullnode2.chronicle.rpc.StringArray build() {
			one.inve.localfullnode2.chronicle.rpc.StringArray result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public one.inve.localfullnode2.chronicle.rpc.StringArray buildPartial() {
			one.inve.localfullnode2.chronicle.rpc.StringArray result = new one.inve.localfullnode2.chronicle.rpc.StringArray(
					this);
			int from_bitField0_ = bitField0_;
			if (((bitField0_ & 0x00000001) != 0)) {
				data_ = data_.getUnmodifiableView();
				bitField0_ = (bitField0_ & ~0x00000001);
			}
			result.data_ = data_;
			onBuilt();
			return result;
		}

		public Builder clone() {
			return super.clone();
		}

		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}

		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof one.inve.localfullnode2.chronicle.rpc.StringArray) {
				return mergeFrom((one.inve.localfullnode2.chronicle.rpc.StringArray) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(one.inve.localfullnode2.chronicle.rpc.StringArray other) {
			if (other == one.inve.localfullnode2.chronicle.rpc.StringArray.getDefaultInstance())
				return this;
			if (!other.data_.isEmpty()) {
				if (data_.isEmpty()) {
					data_ = other.data_;
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					ensureDataIsMutable();
					data_.addAll(other.data_);
				}
				onChanged();
			}
			this.mergeUnknownFields(other.unknownFields);
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			one.inve.localfullnode2.chronicle.rpc.StringArray parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (one.inve.localfullnode2.chronicle.rpc.StringArray) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private int bitField0_;

		private com.google.protobuf.LazyStringList data_ = com.google.protobuf.LazyStringArrayList.EMPTY;

		private void ensureDataIsMutable() {
			if (!((bitField0_ & 0x00000001) != 0)) {
				data_ = new com.google.protobuf.LazyStringArrayList(data_);
				bitField0_ |= 0x00000001;
			}
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @return A list containing the data.
		 */
		public com.google.protobuf.ProtocolStringList getDataList() {
			return data_.getUnmodifiableView();
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @return The count of data.
		 */
		public int getDataCount() {
			return data_.size();
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @param index The index of the element to return.
		 * @return The data at the given index.
		 */
		public java.lang.String getData(int index) {
			return data_.get(index);
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @param index The index of the value to return.
		 * @return The bytes of the data at the given index.
		 */
		public com.google.protobuf.ByteString getDataBytes(int index) {
			return data_.getByteString(index);
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @param index The index to set the value at.
		 * @param value The data to set.
		 * @return This builder for chaining.
		 */
		public Builder setData(int index, java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureDataIsMutable();
			data_.set(index, value);
			onChanged();
			return this;
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @param value The data to add.
		 * @return This builder for chaining.
		 */
		public Builder addData(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}
			ensureDataIsMutable();
			data_.add(value);
			onChanged();
			return this;
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @param values The data to add.
		 * @return This builder for chaining.
		 */
		public Builder addAllData(java.lang.Iterable<java.lang.String> values) {
			ensureDataIsMutable();
			com.google.protobuf.AbstractMessageLite.Builder.addAll(values, data_);
			onChanged();
			return this;
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @return This builder for chaining.
		 */
		public Builder clearData() {
			data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			bitField0_ = (bitField0_ & ~0x00000001);
			onChanged();
			return this;
		}

		/**
		 * <code>repeated string data = 1;</code>
		 * 
		 * @param value The bytes of the data to add.
		 * @return This builder for chaining.
		 */
		public Builder addDataBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);
			ensureDataIsMutable();
			data_.add(value);
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:rpc.StringArray)
	}

	// @@protoc_insertion_point(class_scope:rpc.StringArray)
	private static final one.inve.localfullnode2.chronicle.rpc.StringArray DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new one.inve.localfullnode2.chronicle.rpc.StringArray();
	}

	public static one.inve.localfullnode2.chronicle.rpc.StringArray getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<StringArray> PARSER = new com.google.protobuf.AbstractParser<StringArray>() {

		public StringArray parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new StringArray(input, extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<StringArray> parser() {
		return PARSER;
	}

	public com.google.protobuf.Parser<StringArray> getParserForType() {
		return PARSER;
	}

	public one.inve.localfullnode2.chronicle.rpc.StringArray getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
