// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package one.inve.localfullnode2.chronicle.rpc;

public interface StringArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.StringArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string data = 1;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.String>
      getDataList();
  /**
   * <code>repeated string data = 1;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated string data = 1;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  java.lang.String getData(int index);
  /**
   * <code>repeated string data = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the data at the given index.
   */
  com.google.protobuf.ByteString
      getDataBytes(int index);
}
