// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: misc.proto

package one.inve.localfullnode2.chronicle.rpc;

public interface WrappedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.WrappedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageType = 1;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>bytes messageBody = 2;</code>
   * @return The messageBody.
   */
  com.google.protobuf.ByteString getMessageBody();
}
