// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `Hashnet.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package one.inve.rpc.localfullnode;

public class Hash implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String hash;

    public int hashMapSeed;

    public Hash()
    {
        this.hash = "";
    }

    public Hash(String hash, int hashMapSeed)
    {
        this.hash = hash;
        this.hashMapSeed = hashMapSeed;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Hash r = null;
        if(rhs instanceof Hash)
        {
            r = (Hash)rhs;
        }

        if(r != null)
        {
            if(this.hash != r.hash)
            {
                if(this.hash == null || r.hash == null || !this.hash.equals(r.hash))
                {
                    return false;
                }
            }
            if(this.hashMapSeed != r.hashMapSeed)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::one::inve::rpc::localfullnode::Hash");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, hash);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, hashMapSeed);
        return h_;
    }

    public Hash clone()
    {
        Hash c = null;
        try
        {
            c = (Hash)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.hash);
        ostr.writeInt(this.hashMapSeed);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.hash = istr.readString();
        this.hashMapSeed = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Hash v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Hash ice_read(com.zeroc.Ice.InputStream istr)
    {
        Hash v = new Hash();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Hash> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Hash v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Hash> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Hash.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Hash _nullMarshalValue = new Hash();

    public static final long serialVersionUID = -2633761091055884483L;
}
