// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ByteStream struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteStream) Reset()         { *m = ByteStream{} }
func (m *ByteStream) String() string { return proto.CompactTextString(m) }
func (*ByteStream) ProtoMessage()    {}
func (*ByteStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *ByteStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteStream.Unmarshal(m, b)
}
func (m *ByteStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteStream.Marshal(b, m, deterministic)
}
func (m *ByteStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteStream.Merge(m, src)
}
func (m *ByteStream) XXX_Size() int {
	return xxx_messageInfo_ByteStream.Size(m)
}
func (m *ByteStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteStream.DiscardUnknown(m)
}

var xxx_messageInfo_ByteStream proto.InternalMessageInfo

func (m *ByteStream) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StringArray struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ByteStream)(nil), "rpc.ByteStream")
	proto.RegisterType((*StringArray)(nil), "rpc.StringArray")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x52, 0xe0,
	0xe2, 0x72, 0xaa, 0x2c, 0x49, 0x0d, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0x15, 0x12, 0xe2, 0x62, 0x49,
	0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x09, 0x02, 0xb3, 0x95, 0x14, 0xb9, 0xb8,
	0x83, 0x4b, 0x8a, 0x32, 0xf3, 0xd2, 0x1d, 0x8b, 0x8a, 0x12, 0x2b, 0x51, 0x94, 0x70, 0x42, 0x94,
	0x38, 0x69, 0x72, 0xa9, 0xe6, 0xe7, 0xa5, 0xea, 0x65, 0xe6, 0x95, 0xa5, 0xea, 0xe5, 0xe4, 0x27,
	0x27, 0xe6, 0xa4, 0x95, 0xe6, 0xe4, 0xe4, 0xe5, 0xa7, 0xa4, 0x1a, 0xe9, 0x25, 0x67, 0x14, 0xe5,
	0xe7, 0x65, 0x26, 0xe7, 0xa4, 0xea, 0x15, 0x15, 0x24, 0x07, 0x30, 0x26, 0xb1, 0x81, 0xed, 0x36,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x60, 0x30, 0xae, 0x03, 0x8b, 0x00, 0x00, 0x00,
}
