// Code generated by protoc-gen-go. DO NOT EDIT.
// source: misc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//TODO: attach signature to WrappedMessage
type WrappedMessage struct {
	MessageType          int32    `protobuf:"varint,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	MessageBody          []byte   `protobuf:"bytes,2,opt,name=messageBody,proto3" json:"messageBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrappedMessage) Reset()         { *m = WrappedMessage{} }
func (m *WrappedMessage) String() string { return proto.CompactTextString(m) }
func (*WrappedMessage) ProtoMessage()    {}
func (*WrappedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3ba2f07ad357c5, []int{0}
}

func (m *WrappedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrappedMessage.Unmarshal(m, b)
}
func (m *WrappedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrappedMessage.Marshal(b, m, deterministic)
}
func (m *WrappedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrappedMessage.Merge(m, src)
}
func (m *WrappedMessage) XXX_Size() int {
	return xxx_messageInfo_WrappedMessage.Size(m)
}
func (m *WrappedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WrappedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WrappedMessage proto.InternalMessageInfo

func (m *WrappedMessage) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *WrappedMessage) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func init() {
	proto.RegisterType((*WrappedMessage)(nil), "rpc.WrappedMessage")
}

func init() { proto.RegisterFile("misc.proto", fileDescriptor_2d3ba2f07ad357c5) }

var fileDescriptor_2d3ba2f07ad357c5 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcd, 0x2c, 0x4e,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x0a, 0xe1, 0xe2, 0x0b,
	0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x4d, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x52, 0xe0,
	0xe2, 0xce, 0x85, 0x30, 0x43, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x90,
	0x85, 0x90, 0x54, 0x38, 0xe5, 0xa7, 0x54, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x0b,
	0x39, 0x69, 0x72, 0xa9, 0xe6, 0xe7, 0xa5, 0xea, 0x65, 0xe6, 0x95, 0xa5, 0xea, 0xe5, 0xe4, 0x27,
	0x27, 0xe6, 0xa4, 0x95, 0xe6, 0xe4, 0xe4, 0xe5, 0xa7, 0xa4, 0x1a, 0xe9, 0x25, 0x67, 0x14, 0xe5,
	0xe7, 0x65, 0x26, 0xe7, 0xa4, 0xea, 0x15, 0x15, 0x24, 0x07, 0x30, 0x26, 0xb1, 0x81, 0x1d, 0x63,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x0d, 0xff, 0x5c, 0x9a, 0x00, 0x00, 0x00,
}
